version: '2'
services:
    bastion:
        image: wato-bastion
        build: .
        ports:
            - '22:22'
        environment:
            - MFA_PROVIDER=none
        volumes:
            # Files required by the guest are
            # - /etc/passwd
            # - /etc/shadow,
            # - /etc/group.
            # Mounting the entire /etc instead of the individual files so that
            # changes to the files can reflect in the container:
            # https://stackoverflow.com/a/53548078
            # https://github.com/moby/moby/issues/15793#issuecomment-512913198
            - '/etc:/etc.host:ro'
            - '/home:/home'
            - './secrets/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro'
            - './secrets/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro'
        hostname: wato-bastion-secure
        networks: [ipv6network]
        dns:
            # wato cluster DNS
            - 10.0.50.254
            # Public DNS
            - 1.1.1.1
            - 1.0.0.1
        logging:
          driver: "syslog"
          options:
            syslog-facility: "auth"
            tag: "docker-bastion"
        restart: unless-stopped
    ipv6nat:
        image: robbertkl/ipv6nat
        command: -debug -cleanup
        restart: unless-stopped
        cap_drop: [ ALL ]
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        network_mode: host
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/lib/modules:/lib/modules:ro'
networks:
    ipv6network:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: fd00:dead:beef::/48

