version: '3.9'
services:
    bastion:
        image: wato-bastion
        build: .
        ports:
            - '22:22'
        environment:
            - MFA_PROVIDER=none
        volumes:
            - '/etc/passwd:/etc/passwd.host:ro'
            - '/etc/shadow:/etc/shadow:ro'
            - '/etc/group:/etc/group:ro'
            - '/home:/home'
            - './secrets/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro'
            - './secrets/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro'
        hostname: wato-bastion-secure
        dns:
            # wato cluster DNS
            - 10.0.50.254
            # UWaterloo DNS
            - 129.97.2.1
            - 129.97.2.2

