#!/bin/bash

if [ "${SSH_AUDIT_ENABLED}" == "true" ]; then
	echo "- Enabling SSH Audit Logs"
	cat <<-EOF >/etc/sudoers.d/sudosh
		Defaults log_output
		Defaults!/usr/bin/sudoreplay !log_output
		Defaults!REBOOT !log_output
	EOF
	echo "# valid login shells" > /etc/shells
	echo "/usr/bin/sudosh" >> /etc/shells
	echo "session requisite pam_exec.so quiet /usr/bin/sudosh-add-user" > /etc/pam.d/sudosh
	if [ -w /etc/passwd ]; then
                usermod -s /usr/bin/sudosh root
	fi
else
	echo "- Disabling SSH Audit Logs"
	:>/etc/pam.d/sudosh
fi


